nelmio_api_doc:
    documentation:
        info:
            title: vgmq-api
            description: ~
            version: 0.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!(($)|(_.)))
