version:  '3.7'
services:
  db:
    image: mysql:8.0
    container_name: vgmq-api-db
    ports:
      - '3306:3306'
    volumes:
      - './.data/db:/var/lib/mysql'
    environment:
      MYSQL_USER:          admin
      MYSQL_PASSWORD:      ok
      MYSQL_ROOT_PASSWORD: ok
      MYSQL_DATABASE: vgmq
    networks:
      - main
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vgmq-api-phpmyadmin
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - main
  nginx:
    image: nginx:1.15.3-alpine
    container_name: vgmq-api-nginx
    volumes:
      - './public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
      - php
    networks:
      - main
  php:
    container_name: vgmq-api-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/usr/src/app
    networks:
      - main

networks:
  main:
