controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:   /

admin:
    resource: ../../src/Controller/Admin
    type: annotation
    prefix: /admin

kernel:
    resource: ../../src/Kernel.php
    type: annotation
