App\Entity\Lobby:
    attributes:
        code:
            groups: ['lobby_user', 'lobby_list']
        name:
            groups: ['lobby_user', 'lobby_list']
        password:
            groups: [ 'lobby_user' ]
        hasPassword:
            groups: ['lobby_user', 'lobby_list']
        status:
            groups: [ 'lobby_user', 'lobby_list' ]
        users:
            groups: [ 'lobby_user', 'lobby_list' ]
        countMusics:
            groups: [ 'lobby_user', 'lobby_list' ]
        currentMusic:
            groups: [ 'lobby_user', 'lobby_list' ]
        guessTime:
            groups: [ 'lobby_user', 'lobby_list' ]
        musicNumber:
            groups: [ 'lobby_user' ]
        allowDuplicates:
            groups: [ 'lobby_user' ]
