App\Entity\LobbyUser:
    attributes:
        user:
            groups: ['lobby_user', 'lobby_list']
        role:
            groups: ['lobby_user', 'lobby_list']
        answer:
            groups: ['lobby_answer_reveal']
        answered:
            groups: ['lobby_user']
